# Generated by Django 4.1.7 on 2023-03-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lessons_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
    ]
